version: '3'

services:
  nodejs:
    build: .
    ports:
      - "30003:30003"
    environment:
      - NODE_ENV=production

  database:
    image: mongo
    ports:
      - "27017:27017"

#  swagger:
#    image: swaggerapi/swagger-ui
#    ports:
#      - "4000:8080"
#    environment:
#      - SWAGGER_JSON=http://0.0.0.0:30003/swagger.json
